"""集中管理常用提示文案，便于统一修改或后续多语言扩展。"""

# 登录相关
LOGIN_REQUIRED_TITLE = "提示"
LOGIN_REQUIRED_MESSAGE = "请先登录"
LOGIN_REQUIRED_BEFORE_PURCHASE = "请先登录后再购买会员"
LOGIN_REQUIRED_BEFORE_UPLOAD_AVATAR = "请先登录后再尝试上传头像"
LOGIN_EMAIL_INVALID_TITLE = "邮箱格式错误"
LOGIN_EMAIL_INVALID_MESSAGE = "请输入有效的邮箱地址"
LOGIN_USERNAME_REQUIRED_TITLE = "用户名缺失"
LOGIN_USERNAME_REQUIRED_MESSAGE = "请输入用户名"
LOGIN_PASSWORD_INVALID_TITLE = "密码格式错误"
LOGIN_PASSWORD_INVALID_MESSAGE = "密码应包含大小写字母、数字和特殊字符，长度至少8位"
LOGIN_VERIFICATION_INVALID_TITLE = "验证码错误"
LOGIN_VERIFICATION_INVALID_MESSAGE = "验证码已过期或不正确，请重新获取"
LOGIN_USER_EXISTS_TITLE = "用户已存在"
LOGIN_USER_EXISTS_MESSAGE = "用户已存在，请直接登录"
LOGIN_REGISTER_FAILED_TITLE = "注册失败"
LOGIN_REGISTER_FAILED_MESSAGE = "注册失败，请稍后重试"
LOGIN_FAILED_TITLE = "登录失败"
LOGIN_PASSWORD_WRONG_MESSAGE = "密码错误，请重试"
LOGIN_USER_NOT_FOUND_MESSAGE = "用户不存在，请先注册"
LOGIN_FAILED_MESSAGE = "登录失败，请稍后重试"

# 会员 / 钻石相关
DIAMOND_NOT_ENOUGH_TITLE = "钻石不足"
DIAMOND_NOT_ENOUGH_MESSAGE = "您的钻石数量不足，无法完成本次操作，请先前往充值钻石。"
DIAMOND_NOT_ENOUGH_FOR_VIP_MESSAGE = "您的钻石数量不足，无法购买该会员套餐，请先前往充值钻石。"

VIP_PURCHASE_FAILED_TITLE = "购买失败"
VIP_PURCHASE_FAILED_MESSAGE = "购买会员失败，请稍后重试或联系管理员。"
VIP_PURCHASE_SUCCESS_TITLE = "购买成功"
VIP_PURCHASE_SUCCESS_MESSAGE_TEMPLATE = "已成功开通 {name}，感谢您的支持！"

# 通用错误
GENERIC_ERROR_TITLE = "错误"
GENERIC_RETRY_LATER_MESSAGE = "操作失败，请稍后重试。"

